import type { CardCatalogEntry } from "@/types";

export const CARD_CATALOG: CardCatalogEntry[] = [
  // ─── PREMIUM TRAVEL ───────────────────────────────────────────────
  {
    id: "amex-platinum",
    name: "American Express Platinum",
    issuer: "American Express",
    annualFee: 695,
    tier: "premium",
    verified: true,
    color: "from-gray-700 to-gray-900",
    benefits: [
      {
        id: "amex-plat-uber-cash",
        cardId: "amex-platinum",
        name: "Uber Cash",
        description: "$15/month Uber Cash ($35 in December) for Uber rides and Uber Eats.",
        dollarValue: 200,
        resetFrequency: "monthly",
        category: "statement-credit",
        activationRequired: true,
        redemptionInstructions: "Add your Amex Platinum as a payment method in the Uber app. Uber Cash is automatically credited each month.",
        expiresAt: "2026-12-31",
      },
      {
        id: "amex-plat-airline",
        cardId: "amex-platinum",
        name: "Airline Fee Credit",
        description: "$200 annual statement credit for incidental airline fees on one selected airline.",
        dollarValue: 200,
        resetFrequency: "annual",
        category: "statement-credit",
        activationRequired: true,
        redemptionInstructions: "Log into amextravel.com and select your preferred airline. Charges for seat upgrades, checked bags, and in-flight purchases are automatically credited.",
        expiresAt: "2026-12-31",
      },
      {
        id: "amex-plat-hotel",
        cardId: "amex-platinum",
        name: "Fine Hotels + Resorts / Hotel Credit",
        description: "$200 hotel credit for prepaid bookings through American Express Travel.",
        dollarValue: 200,
        resetFrequency: "annual",
        category: "statement-credit",
        activationRequired: false,
        redemptionInstructions: "Book a qualifying hotel through AmexTravel.com using your Platinum card. The credit applies automatically.",
        expiresAt: "2026-12-31",
      },
      {
        id: "amex-plat-clear",
        cardId: "amex-platinum",
        name: "CLEAR Plus Credit",
        description: "$189 annual credit for CLEAR Plus airport biometric security membership.",
        dollarValue: 189,
        resetFrequency: "annual",
        category: "membership",
        activationRequired: false,
        redemptionInstructions: "Sign up or renew CLEAR Plus at clearme.com and pay with your Amex Platinum. The credit posts automatically.",
        expiresAt: "2026-12-31",
      },
      {
        id: "amex-plat-walmart",
        cardId: "amex-platinum",
        name: "Walmart+ Credit",
        description: "$12.95/month statement credit for a Walmart+ membership.",
        dollarValue: 155,
        resetFrequency: "monthly",
        category: "membership",
        activationRequired: false,
        redemptionInstructions: "Pay for your Walmart+ membership with your Amex Platinum card. The credit posts automatically each month.",
        expiresAt: "2026-12-31",
      },
      {
        id: "amex-plat-digital",
        cardId: "amex-platinum",
        name: "Digital Entertainment Credit",
        description: "$20/month for select streaming and digital services (Disney+, Hulu, ESPN+, Peacock, The New York Times, SiriusXM).",
        dollarValue: 240,
        resetFrequency: "monthly",
        category: "statement-credit",
        activationRequired: false,
        redemptionInstructions: "Pay for qualifying digital subscriptions with your Amex Platinum. Credits post automatically.",
        expiresAt: "2026-12-31",
      },
      {
        id: "amex-plat-saks",
        cardId: "amex-platinum",
        name: "Saks Fifth Avenue Credit",
        description: "$50 credit semi-annually ($100/year) for purchases at Saks Fifth Avenue.",
        dollarValue: 100,
        resetFrequency: "semi-annual",
        resetMonths: [1, 7],
        category: "statement-credit",
        activationRequired: false,
        redemptionInstructions: "Shop at Saks Fifth Avenue (in-store or online) and pay with your Amex Platinum. Credit posts automatically.",
        expiresAt: "2026-06-30",
      },
      {
        id: "amex-plat-lounge",
        cardId: "amex-platinum",
        name: "Global Lounge Collection",
        description: "Complimentary access to 1,400+ airport lounges worldwide including Centurion Lounges, Delta Sky Clubs, Priority Pass, and more.",
        dollarValue: 300,
        resetFrequency: "annual",
        category: "lounge",
        activationRequired: false,
        redemptionInstructions: "Show your Amex Platinum card at any participating lounge. For Priority Pass lounges, enroll at prioritypass.com first.",
        expiresAt: "2026-12-31",
      },
    ],
  },

  {
    id: "chase-sapphire-reserve",
    name: "Chase Sapphire Reserve",
    issuer: "Chase",
    annualFee: 550,
    tier: "premium",
    verified: true,
    color: "from-slate-800 to-blue-900",
    benefits: [
      {
        id: "csr-travel-credit",
        cardId: "chase-sapphire-reserve",
        name: "$300 Annual Travel Credit",
        description: "$300 statement credit for travel purchases — the broadest definition of travel in the industry.",
        dollarValue: 300,
        resetFrequency: "annual",
        category: "statement-credit",
        activationRequired: false,
        redemptionInstructions: "Use your Chase Sapphire Reserve for any travel purchase (airlines, hotels, Airbnb, Uber, parking, tolls). First $300 in travel charges each year are automatically credited.",
        expiresAt: "2026-12-31",
      },
      {
        id: "csr-lounge",
        cardId: "chase-sapphire-reserve",
        name: "Priority Pass Lounge Access",
        description: "Complimentary Priority Pass Select membership with access to 1,300+ airport lounges globally.",
        dollarValue: 250,
        resetFrequency: "annual",
        category: "lounge",
        activationRequired: true,
        redemptionInstructions: "Activate your Priority Pass through the Chase benefits portal at chase.com/benefits. Then show your Priority Pass card at participating lounges.",
        expiresAt: "2026-12-31",
      },
      {
        id: "csr-hotel-perks",
        cardId: "chase-sapphire-reserve",
        name: "The Edit / Hotel Collection Perks",
        description: "Complimentary amenities at boutique hotels in The Edit collection — room upgrade when available, complimentary breakfast, and a special amenity per stay.",
        dollarValue: 150,
        resetFrequency: "annual",
        category: "bonus",
        activationRequired: false,
        redemptionInstructions: "Book through The Edit collection on chase.com/travel using your Sapphire Reserve. Perks are applied automatically at check-in.",
        expiresAt: "2026-12-31",
      },
      {
        id: "csr-rental-car",
        cardId: "chase-sapphire-reserve",
        name: "Primary Rental Car Insurance",
        description: "Primary rental car collision damage waiver — no need to file against your personal auto insurance.",
        dollarValue: 75,
        resetFrequency: "annual",
        category: "insurance",
        activationRequired: false,
        redemptionInstructions: "Decline the rental company's collision damage waiver and pay with your Chase Sapphire Reserve. Coverage is automatic.",
        expiresAt: "2026-12-31",
      },
    ],
  },

  {
    id: "capital-one-venture-x",
    name: "Capital One Venture X",
    issuer: "Capital One",
    annualFee: 395,
    tier: "premium",
    verified: true,
    color: "from-red-700 to-red-900",
    benefits: [
      {
        id: "venturex-travel-credit",
        cardId: "capital-one-venture-x",
        name: "$300 Capital One Travel Credit",
        description: "$300 annual credit for bookings made through Capital One Travel portal.",
        dollarValue: 300,
        resetFrequency: "annual",
        category: "statement-credit",
        activationRequired: false,
        redemptionInstructions: "Book hotels, flights, or car rentals through travel.capitalone.com. The credit applies automatically.",
        expiresAt: "2026-12-31",
      },
      {
        id: "venturex-bonus-miles",
        cardId: "capital-one-venture-x",
        name: "10,000 Bonus Miles Anniversary",
        description: "10,000 bonus miles each account anniversary (worth ~$100 in travel).",
        dollarValue: 100,
        resetFrequency: "annual",
        category: "bonus",
        activationRequired: false,
        redemptionInstructions: "Miles are automatically credited each year on your account anniversary. Redeem through Capital One Travel or transfer to 15+ partners.",
        expiresAt: "2026-12-31",
      },
      {
        id: "venturex-lounge",
        cardId: "capital-one-venture-x",
        name: "Capital One & Priority Pass Lounge Access",
        description: "Unlimited access to Capital One Lounges and Priority Pass network (1,300+ lounges), plus 2 guest passes.",
        dollarValue: 200,
        resetFrequency: "annual",
        category: "lounge",
        activationRequired: true,
        redemptionInstructions: "Enroll in Priority Pass through your Capital One account. Capital One Lounges are accessible by showing your Venture X card.",
        expiresAt: "2026-12-31",
      },
    ],
  },

  // ─── MID-TIER REWARDS ─────────────────────────────────────────────
  {
    id: "chase-sapphire-preferred",
    name: "Chase Sapphire Preferred",
    issuer: "Chase",
    annualFee: 95,
    tier: "mid-tier",
    verified: true,
    color: "from-blue-600 to-blue-800",
    benefits: [
      {
        id: "csp-hotel-credit",
        cardId: "chase-sapphire-preferred",
        name: "$50 Annual Hotel Credit",
        description: "$50 statement credit for hotel stays booked through Chase Travel.",
        dollarValue: 50,
        resetFrequency: "annual",
        category: "statement-credit",
        activationRequired: false,
        redemptionInstructions: "Book a hotel through chase.com/travel and pay with your Sapphire Preferred. The $50 credit posts automatically.",
        expiresAt: "2026-12-31",
      },
      {
        id: "csp-dashpass",
        cardId: "chase-sapphire-preferred",
        name: "DoorDash DashPass",
        description: "Complimentary DashPass membership (normally $9.99/month) with $0 delivery fees.",
        dollarValue: 120,
        resetFrequency: "annual",
        category: "membership",
        activationRequired: true,
        redemptionInstructions: "Activate DashPass in the DoorDash app under Account → DashPass. Select 'Activate with Chase' and link your Sapphire Preferred.",
        expiresAt: "2026-12-31",
      },
      {
        id: "csp-rental-car",
        cardId: "chase-sapphire-preferred",
        name: "Primary Rental Car Coverage",
        description: "Primary rental car collision damage waiver on rentals paid with your card.",
        dollarValue: 60,
        resetFrequency: "annual",
        category: "insurance",
        activationRequired: false,
        redemptionInstructions: "Decline the rental counter's CDW and pay with your Sapphire Preferred. Coverage applies automatically.",
        expiresAt: "2026-12-31",
      },
    ],
  },

  {
    id: "amex-gold",
    name: "American Express Gold",
    issuer: "American Express",
    annualFee: 325,
    tier: "mid-tier",
    verified: true,
    color: "from-yellow-600 to-yellow-800",
    benefits: [
      {
        id: "amex-gold-uber-cash",
        cardId: "amex-gold",
        name: "Uber Cash",
        description: "$10/month Uber Cash for Uber rides and Uber Eats ($120/year).",
        dollarValue: 120,
        resetFrequency: "monthly",
        category: "statement-credit",
        activationRequired: true,
        redemptionInstructions: "Add your Amex Gold as a payment method in the Uber app. $10 Uber Cash is automatically credited each month.",
        expiresAt: "2026-12-31",
      },
      {
        id: "amex-gold-dining",
        cardId: "amex-gold",
        name: "Dining Credit",
        description: "$10/month statement credit at participating restaurants including Grubhub, The Cheesecake Factory, Goldbelly, Wine.com, and Five Guys ($120/year).",
        dollarValue: 120,
        resetFrequency: "monthly",
        category: "statement-credit",
        activationRequired: false,
        redemptionInstructions: "Pay at any participating restaurant with your Amex Gold. Credits post automatically each month.",
        expiresAt: "2026-12-31",
      },
      {
        id: "amex-gold-resy",
        cardId: "amex-gold",
        name: "Resy Dining Credit",
        description: "$50 semi-annually ($100/year) at Resy-booked restaurants.",
        dollarValue: 100,
        resetFrequency: "semi-annual",
        resetMonths: [1, 7],
        category: "statement-credit",
        activationRequired: false,
        redemptionInstructions: "Book a restaurant through the Resy app or website and pay with your Amex Gold. Credit applies automatically for qualifying purchases.",
        expiresAt: "2026-06-30",
      },
      {
        id: "amex-gold-dunkin",
        cardId: "amex-gold",
        name: "Dunkin' Credit",
        description: "$7/month ($84/year) statement credit at Dunkin' locations.",
        dollarValue: 84,
        resetFrequency: "monthly",
        category: "statement-credit",
        activationRequired: false,
        redemptionInstructions: "Pay at any Dunkin' location with your Amex Gold card. Credit posts automatically each month.",
        expiresAt: "2026-12-31",
      },
    ],
  },

  {
    id: "capital-one-venture",
    name: "Capital One Venture",
    issuer: "Capital One",
    annualFee: 95,
    tier: "mid-tier",
    verified: true,
    color: "from-red-600 to-red-800",
    benefits: [
      {
        id: "venture-travel-credit",
        cardId: "capital-one-venture",
        name: "Global Entry/TSA PreCheck Credit",
        description: "$100 credit for Global Entry ($120) or TSA PreCheck ($85) application fee every 4 years.",
        dollarValue: 100,
        resetFrequency: "one-time",
        category: "statement-credit",
        activationRequired: false,
        redemptionInstructions: "Pay the Global Entry or TSA PreCheck application fee with your Capital One Venture card. Credit posts automatically.",
        expiresAt: "2026-12-31",
      },
    ],
  },

  {
    id: "citi-strata-premier",
    name: "Citi Strata Premier",
    issuer: "Citi",
    annualFee: 95,
    tier: "mid-tier",
    verified: true,
    color: "from-blue-500 to-indigo-700",
    benefits: [
      {
        id: "citi-hotel-credit",
        cardId: "citi-strata-premier",
        name: "$100 Annual Hotel Credit",
        description: "$100 statement credit for single hotel stays of $500+ booked through CitiTravel.com.",
        dollarValue: 100,
        resetFrequency: "annual",
        category: "statement-credit",
        activationRequired: false,
        redemptionInstructions: "Book a hotel stay of $500+ through CitiTravel.com and pay with your Citi Strata Premier. The $100 credit posts automatically.",
        expiresAt: "2026-12-31",
      },
    ],
  },

  // ─── CASH BACK ────────────────────────────────────────────────────
  {
    id: "chase-freedom-unlimited",
    name: "Chase Freedom Unlimited",
    issuer: "Chase",
    annualFee: 0,
    tier: "cash-back",
    verified: true,
    color: "from-blue-400 to-blue-600",
    benefits: [
      {
        id: "cfu-dashpass",
        cardId: "chase-freedom-unlimited",
        name: "DoorDash DashPass",
        description: "Complimentary DashPass for 3 months, then 50% off for the next 9 months.",
        dollarValue: 30,
        resetFrequency: "one-time",
        category: "membership",
        activationRequired: true,
        redemptionInstructions: "Activate in the DoorDash app under Account → DashPass. Select 'Activate with Chase' and link your Freedom Unlimited.",
        expiresAt: "2026-12-31",
      },
    ],
  },

  {
    id: "chase-freedom-flex",
    name: "Chase Freedom Flex",
    issuer: "Chase",
    annualFee: 0,
    tier: "cash-back",
    verified: true,
    color: "from-cyan-500 to-blue-600",
    benefits: [
      {
        id: "cff-5pct-quarterly",
        cardId: "chase-freedom-flex",
        name: "5% Rotating Categories (Quarterly)",
        description: "5% cash back on up to $1,500 in combined purchases in activated quarterly categories. Categories rotate each quarter — check chase.com/activate for current categories.",
        dollarValue: 75,
        resetFrequency: "quarterly",
        category: "rewards",
        activationRequired: true,
        redemptionInstructions: "Activate each quarter at chase.com/activate before the deadline. Then use your Freedom Flex for purchases in the bonus categories.",
        expiresAt: "2026-06-30",
      },
      {
        id: "cff-cell-protection",
        cardId: "chase-freedom-flex",
        name: "Cell Phone Protection",
        description: "Up to $800 per claim ($1,000/year) for cell phone damage or theft when you pay your monthly bill with this card.",
        dollarValue: 200,
        resetFrequency: "annual",
        category: "protection",
        activationRequired: false,
        redemptionInstructions: "Pay your monthly cell phone bill with your Freedom Flex card. If your phone is damaged or stolen, file a claim at eclaimsline.com.",
        expiresAt: "2026-12-31",
      },
    ],
  },

  {
    id: "citi-double-cash",
    name: "Citi Double Cash",
    issuer: "Citi",
    annualFee: 0,
    tier: "cash-back",
    verified: true,
    color: "from-gray-500 to-gray-700",
    benefits: [],
  },

  {
    id: "wells-fargo-active-cash",
    name: "Wells Fargo Active Cash",
    issuer: "Wells Fargo",
    annualFee: 0,
    tier: "cash-back",
    verified: true,
    color: "from-red-500 to-yellow-600",
    benefits: [
      {
        id: "wfac-cell-protection",
        cardId: "wells-fargo-active-cash",
        name: "Cell Phone Protection",
        description: "Up to $600 per claim for cell phone damage or theft when you pay your monthly bill with this card.",
        dollarValue: 150,
        resetFrequency: "annual",
        category: "protection",
        activationRequired: false,
        redemptionInstructions: "Pay your monthly cell phone bill with your Active Cash card. File claims at eclaimsline.com if damage or theft occurs.",
        expiresAt: "2026-12-31",
      },
    ],
  },

  {
    id: "capital-one-savor",
    name: "Capital One Savor",
    issuer: "Capital One",
    annualFee: 95,
    tier: "cash-back",
    verified: true,
    color: "from-green-600 to-teal-700",
    benefits: [
      {
        id: "savor-uber-eats",
        cardId: "capital-one-savor",
        name: "Uber Eats Benefit",
        description: "$10/month Uber Eats credit ($120/year) for Uber Eats orders.",
        dollarValue: 120,
        resetFrequency: "monthly",
        category: "statement-credit",
        activationRequired: true,
        redemptionInstructions: "Link your Capital One Savor in the Uber app. $10 Uber Eats credit is automatically applied each month.",
        expiresAt: "2026-12-31",
      },
    ],
  },

  {
    id: "discover-it-cash-back",
    name: "Discover it Cash Back",
    issuer: "Discover",
    annualFee: 0,
    tier: "cash-back",
    verified: true,
    color: "from-orange-400 to-orange-600",
    benefits: [
      {
        id: "discover-5pct-quarterly",
        cardId: "discover-it-cash-back",
        name: "5% Rotating Categories (Quarterly)",
        description: "5% cash back on up to $1,500 in quarterly categories. Categories rotate each quarter — check discover.com/activate for current categories.",
        dollarValue: 75,
        resetFrequency: "quarterly",
        category: "rewards",
        activationRequired: true,
        redemptionInstructions: "Activate at discover.com/activate or in the Discover app before the quarter ends. Use your card for purchases in the bonus categories.",
        expiresAt: "2026-06-30",
      },
    ],
  },

  {
    id: "amex-blue-cash-preferred",
    name: "Amex Blue Cash Preferred",
    issuer: "American Express",
    annualFee: 95,
    tier: "cash-back",
    verified: true,
    color: "from-blue-400 to-indigo-600",
    benefits: [
      {
        id: "abcp-disney",
        cardId: "amex-blue-cash-preferred",
        name: "Disney Bundle Credit",
        description: "$7/month statement credit when you spend $9.99 or more on a Disney Bundle subscription.",
        dollarValue: 84,
        resetFrequency: "monthly",
        category: "statement-credit",
        activationRequired: false,
        redemptionInstructions: "Pay for your Disney Bundle (Disney+, Hulu, ESPN+) with your Amex Blue Cash Preferred. The $7 credit posts automatically.",
        expiresAt: "2026-12-31",
      },
    ],
  },

  {
    id: "amex-blue-cash-everyday",
    name: "Amex Blue Cash Everyday",
    issuer: "American Express",
    annualFee: 0,
    tier: "cash-back",
    verified: true,
    color: "from-sky-400 to-blue-500",
    benefits: [
      {
        id: "abce-disney",
        cardId: "amex-blue-cash-everyday",
        name: "Disney Bundle Credit",
        description: "$7/month statement credit on a Disney Bundle subscription.",
        dollarValue: 84,
        resetFrequency: "monthly",
        category: "statement-credit",
        activationRequired: false,
        redemptionInstructions: "Pay for your Disney Bundle with your Amex Blue Cash Everyday. Credit posts automatically each month.",
        expiresAt: "2026-12-31",
      },
    ],
  },

  {
    id: "capital-one-quicksilver",
    name: "Capital One Quicksilver",
    issuer: "Capital One",
    annualFee: 0,
    tier: "cash-back",
    verified: true,
    color: "from-silver-400 to-gray-500",
    benefits: [],
  },

  {
    id: "bofa-customized-cash",
    name: "Bank of America Customized Cash Rewards",
    issuer: "Bank of America",
    annualFee: 0,
    tier: "cash-back",
    verified: true,
    color: "from-red-600 to-red-800",
    benefits: [],
  },

  {
    id: "macys-credit-card",
    name: "Macy's Credit Card",
    issuer: "Citibank (for Macy's)",
    annualFee: 0,
    tier: "cash-back",
    verified: true,
    color: "from-red-600 to-red-900",
    benefits: [
      {
        id: "macys-star-rewards",
        cardId: "macys-credit-card",
        name: "Star Rewards",
        description: "3% back in Star Money on Macy's purchases, redeemable on future Macy's shopping.",
        dollarValue: 60,
        resetFrequency: "annual",
        category: "rewards",
        activationRequired: false,
        redemptionInstructions: "Star Money is automatically earned on Macy's purchases. Redeem at checkout in-store or online at macys.com.",
        expiresAt: "2026-12-31",
      },
      {
        id: "macys-birthday",
        cardId: "macys-credit-card",
        name: "Birthday Surprise",
        description: "Special birthday offer sent to your email each year — typically 25% off a Macy's purchase.",
        dollarValue: 25,
        resetFrequency: "annual",
        category: "bonus",
        activationRequired: true,
        redemptionInstructions: "Check your email around your birthday for your exclusive offer code. Use at checkout in-store or online.",
        expiresAt: "2026-12-31",
      },
    ],
  },

  // ─── HOTEL & AIRLINE ──────────────────────────────────────────────
  {
    id: "marriott-bonvoy-boundless",
    name: "Marriott Bonvoy Boundless",
    issuer: "Chase",
    annualFee: 95,
    tier: "hotel-airline",
    verified: true,
    color: "from-amber-700 to-amber-900",
    benefits: [
      {
        id: "bonvoy-free-night",
        cardId: "marriott-bonvoy-boundless",
        name: "Annual Free Night Award",
        description: "One free night certificate annually (up to 35,000 points) — valid at thousands of Marriott properties.",
        dollarValue: 150,
        resetFrequency: "annual",
        category: "bonus",
        activationRequired: false,
        redemptionInstructions: "Your free night certificate is deposited into your Bonvoy account each year. Book on the Marriott app or website using 'Redeem Points' at checkout.",
        expiresAt: "2026-12-31",
      },
      {
        id: "bonvoy-silver",
        cardId: "marriott-bonvoy-boundless",
        name: "Silver Elite Status",
        description: "Automatic Marriott Bonvoy Silver Elite status with 10% bonus points and late checkout.",
        dollarValue: 50,
        resetFrequency: "annual",
        category: "status",
        activationRequired: false,
        redemptionInstructions: "Status is automatic with your card. Benefits apply at check-in at any Marriott property worldwide.",
        expiresAt: "2026-12-31",
      },
    ],
  },

  {
    id: "delta-skymiles-gold",
    name: "Delta SkyMiles Gold",
    issuer: "American Express",
    annualFee: 150,
    tier: "hotel-airline",
    verified: true,
    color: "from-blue-700 to-indigo-900",
    benefits: [
      {
        id: "delta-checked-bag",
        cardId: "delta-skymiles-gold",
        name: "First Checked Bag Free",
        description: "First checked bag free for you and up to 8 companions on the same reservation.",
        dollarValue: 180,
        resetFrequency: "annual",
        category: "bonus",
        activationRequired: false,
        redemptionInstructions: "Book Delta flights with your Delta SkyMiles Gold card. First checked bag fee waiver applies automatically at check-in.",
        expiresAt: "2026-12-31",
      },
      {
        id: "delta-bonus-miles",
        cardId: "delta-skymiles-gold",
        name: "10,000 Bonus Miles ($10K Spend)",
        description: "Earn 10,000 bonus SkyMiles after spending $10,000 in a calendar year (~$100 in value).",
        dollarValue: 100,
        resetFrequency: "annual",
        category: "bonus",
        activationRequired: false,
        redemptionInstructions: "Spend $10,000 on your Delta Gold card in a calendar year. 10,000 bonus miles are automatically deposited into your SkyMiles account.",
        expiresAt: "2026-12-31",
      },
    ],
  },

  {
    id: "world-of-hyatt",
    name: "World of Hyatt",
    issuer: "Chase",
    annualFee: 95,
    tier: "hotel-airline",
    verified: true,
    color: "from-stone-700 to-stone-900",
    benefits: [
      {
        id: "hyatt-free-night",
        cardId: "world-of-hyatt",
        name: "Annual Free Night Award",
        description: "One free night annually at any Category 1–4 Hyatt property (up to $200 value).",
        dollarValue: 150,
        resetFrequency: "annual",
        category: "bonus",
        activationRequired: false,
        redemptionInstructions: "Your free night certificate is deposited into your World of Hyatt account each anniversary. Redeem through the Hyatt app or website.",
        expiresAt: "2026-12-31",
      },
      {
        id: "hyatt-discoverist",
        cardId: "world-of-hyatt",
        name: "Discoverist Status",
        description: "Automatic World of Hyatt Discoverist status with 10% bonus points and premium internet.",
        dollarValue: 60,
        resetFrequency: "annual",
        category: "status",
        activationRequired: false,
        redemptionInstructions: "Status is automatic as a cardholder. Benefits apply at Hyatt properties worldwide at check-in.",
        expiresAt: "2026-12-31",
      },
    ],
  },
];

export const getCardById = (id: string): CardCatalogEntry | undefined =>
  CARD_CATALOG.find((c) => c.id === id);

export const getCardsByTier = (tier: string): CardCatalogEntry[] =>
  CARD_CATALOG.filter((c) => c.tier === tier);
