import type { Transaction } from "@/types";

// 90 days of realistic transactions showing suboptimal card usage
// User has: amex-gold, chase-sapphire-preferred, chase-freedom-unlimited
export const MOCK_TRANSACTIONS: Transaction[] = [
  // March 2025
  {
    id: "txn-001",
    date: "2025-03-06",
    merchant: "Whole Foods Market",
    amount: 87.43,
    category: "groceries",
    cardUsed: "chase-freedom-unlimited",
    cardUsedName: "Chase Freedom Unlimited",
    optimalCard: "amex-gold",
    optimalCardName: "Amex Gold",
    missedValue: 2.18,
    isOptimal: false,
  },
  {
    id: "txn-002",
    date: "2025-03-05",
    merchant: "United Airlines",
    amount: 342.00,
    category: "travel",
    cardUsed: "amex-gold",
    cardUsedName: "Amex Gold",
    optimalCard: "chase-sapphire-preferred",
    optimalCardName: "Chase Sapphire Preferred",
    missedValue: 3.42,
    isOptimal: false,
  },
  {
    id: "txn-003",
    date: "2025-03-04",
    merchant: "Nobu Restaurant",
    amount: 185.00,
    category: "dining",
    cardUsed: "amex-gold",
    cardUsedName: "Amex Gold",
    optimalCard: "amex-gold",
    optimalCardName: "Amex Gold",
    missedValue: 0,
    isOptimal: true,
  },
  {
    id: "txn-004",
    date: "2025-03-03",
    merchant: "Uber",
    amount: 23.50,
    category: "travel",
    cardUsed: "chase-freedom-unlimited",
    cardUsedName: "Chase Freedom Unlimited",
    optimalCard: "amex-gold",
    optimalCardName: "Amex Gold",
    missedValue: 0.94,
    isOptimal: false,
  },
  {
    id: "txn-005",
    date: "2025-03-02",
    merchant: "Netflix",
    amount: 22.99,
    category: "streaming",
    cardUsed: "chase-freedom-unlimited",
    cardUsedName: "Chase Freedom Unlimited",
    optimalCard: "amex-blue-cash-preferred",
    optimalCardName: "Amex Blue Cash Preferred",
    missedValue: 0.92,
    isOptimal: false,
  },
  {
    id: "txn-006",
    date: "2025-03-01",
    merchant: "Shell Gas Station",
    amount: 62.00,
    category: "gas",
    cardUsed: "chase-freedom-unlimited",
    cardUsedName: "Chase Freedom Unlimited",
    optimalCard: "amex-blue-cash-preferred",
    optimalCardName: "Amex Blue Cash Preferred",
    missedValue: 0.93,
    isOptimal: false,
  },

  // February 2025
  {
    id: "txn-007",
    date: "2025-02-28",
    merchant: "Trader Joe's",
    amount: 124.67,
    category: "groceries",
    cardUsed: "chase-freedom-unlimited",
    cardUsedName: "Chase Freedom Unlimited",
    optimalCard: "amex-gold",
    optimalCardName: "Amex Gold",
    missedValue: 3.11,
    isOptimal: false,
  },
  {
    id: "txn-008",
    date: "2025-02-27",
    merchant: "Chipotle",
    amount: 18.75,
    category: "dining",
    cardUsed: "chase-freedom-unlimited",
    cardUsedName: "Chase Freedom Unlimited",
    optimalCard: "amex-gold",
    optimalCardName: "Amex Gold",
    missedValue: 0.47,
    isOptimal: false,
  },
  {
    id: "txn-009",
    date: "2025-02-25",
    merchant: "Marriott Boston",
    amount: 289.00,
    category: "travel",
    cardUsed: "chase-sapphire-preferred",
    cardUsedName: "Chase Sapphire Preferred",
    optimalCard: "chase-sapphire-preferred",
    optimalCardName: "Chase Sapphire Preferred",
    missedValue: 0,
    isOptimal: true,
  },
  {
    id: "txn-010",
    date: "2025-02-24",
    merchant: "The Cheesecake Factory",
    amount: 94.20,
    category: "dining",
    cardUsed: "amex-gold",
    cardUsedName: "Amex Gold",
    optimalCard: "amex-gold",
    optimalCardName: "Amex Gold",
    missedValue: 0,
    isOptimal: true,
  },
  {
    id: "txn-011",
    date: "2025-02-22",
    merchant: "Amazon",
    amount: 156.99,
    category: "shopping",
    cardUsed: "chase-freedom-unlimited",
    cardUsedName: "Chase Freedom Unlimited",
    optimalCard: "chase-freedom-unlimited",
    optimalCardName: "Chase Freedom Unlimited",
    missedValue: 0,
    isOptimal: true,
  },
  {
    id: "txn-012",
    date: "2025-02-20",
    merchant: "Spotify",
    amount: 11.99,
    category: "streaming",
    cardUsed: "chase-freedom-unlimited",
    cardUsedName: "Chase Freedom Unlimited",
    optimalCard: "amex-blue-cash-preferred",
    optimalCardName: "Amex Blue Cash Preferred",
    missedValue: 0.48,
    isOptimal: false,
  },
  {
    id: "txn-013",
    date: "2025-02-18",
    merchant: "Sushi Nakazawa",
    amount: 220.00,
    category: "dining",
    cardUsed: "chase-freedom-unlimited",
    cardUsedName: "Chase Freedom Unlimited",
    optimalCard: "amex-gold",
    optimalCardName: "Amex Gold",
    missedValue: 5.50,
    isOptimal: false,
  },
  {
    id: "txn-014",
    date: "2025-02-15",
    merchant: "BP Gas",
    amount: 55.00,
    category: "gas",
    cardUsed: "chase-freedom-unlimited",
    cardUsedName: "Chase Freedom Unlimited",
    optimalCard: "amex-blue-cash-preferred",
    optimalCardName: "Amex Blue Cash Preferred",
    missedValue: 0.83,
    isOptimal: false,
  },
  {
    id: "txn-015",
    date: "2025-02-14",
    merchant: "Eleven Madison Park",
    amount: 310.00,
    category: "dining",
    cardUsed: "amex-gold",
    cardUsedName: "Amex Gold",
    optimalCard: "amex-gold",
    optimalCardName: "Amex Gold",
    missedValue: 0,
    isOptimal: true,
  },
  {
    id: "txn-016",
    date: "2025-02-12",
    merchant: "Whole Foods Market",
    amount: 203.45,
    category: "groceries",
    cardUsed: "chase-freedom-unlimited",
    cardUsedName: "Chase Freedom Unlimited",
    optimalCard: "amex-gold",
    optimalCardName: "Amex Gold",
    missedValue: 5.09,
    isOptimal: false,
  },
  {
    id: "txn-017",
    date: "2025-02-10",
    merchant: "Delta Airlines",
    amount: 489.00,
    category: "travel",
    cardUsed: "amex-gold",
    cardUsedName: "Amex Gold",
    optimalCard: "chase-sapphire-preferred",
    optimalCardName: "Chase Sapphire Preferred",
    missedValue: 4.89,
    isOptimal: false,
  },
  {
    id: "txn-018",
    date: "2025-02-08",
    merchant: "CVS Pharmacy",
    amount: 34.99,
    category: "drugstore",
    cardUsed: "chase-freedom-unlimited",
    cardUsedName: "Chase Freedom Unlimited",
    optimalCard: "chase-freedom-unlimited",
    optimalCardName: "Chase Freedom Unlimited",
    missedValue: 0,
    isOptimal: true,
  },
  {
    id: "txn-019",
    date: "2025-02-05",
    merchant: "Uber Eats",
    amount: 41.30,
    category: "dining",
    cardUsed: "chase-freedom-unlimited",
    cardUsedName: "Chase Freedom Unlimited",
    optimalCard: "amex-gold",
    optimalCardName: "Amex Gold",
    missedValue: 1.03,
    isOptimal: false,
  },
  {
    id: "txn-020",
    date: "2025-02-02",
    merchant: "Target",
    amount: 89.75,
    category: "shopping",
    cardUsed: "chase-freedom-unlimited",
    cardUsedName: "Chase Freedom Unlimited",
    optimalCard: "chase-freedom-unlimited",
    optimalCardName: "Chase Freedom Unlimited",
    missedValue: 0,
    isOptimal: true,
  },

  // January 2025
  {
    id: "txn-021",
    date: "2025-01-30",
    merchant: "Costco",
    amount: 267.88,
    category: "groceries",
    cardUsed: "chase-freedom-unlimited",
    cardUsedName: "Chase Freedom Unlimited",
    optimalCard: "amex-gold",
    optimalCardName: "Amex Gold",
    missedValue: 6.70,
    isOptimal: false,
  },
  {
    id: "txn-022",
    date: "2025-01-28",
    merchant: "Masa Restaurant",
    amount: 450.00,
    category: "dining",
    cardUsed: "chase-freedom-unlimited",
    cardUsedName: "Chase Freedom Unlimited",
    optimalCard: "amex-gold",
    optimalCardName: "Amex Gold",
    missedValue: 11.25,
    isOptimal: false,
  },
  {
    id: "txn-023",
    date: "2025-01-25",
    merchant: "American Airlines",
    amount: 612.00,
    category: "travel",
    cardUsed: "amex-gold",
    cardUsedName: "Amex Gold",
    optimalCard: "chase-sapphire-preferred",
    optimalCardName: "Chase Sapphire Preferred",
    missedValue: 6.12,
    isOptimal: false,
  },
  {
    id: "txn-024",
    date: "2025-01-23",
    merchant: "Hulu",
    amount: 17.99,
    category: "streaming",
    cardUsed: "amex-gold",
    cardUsedName: "Amex Gold",
    optimalCard: "amex-blue-cash-preferred",
    optimalCardName: "Amex Blue Cash Preferred",
    missedValue: 0.72,
    isOptimal: false,
  },
  {
    id: "txn-025",
    date: "2025-01-20",
    merchant: "Shake Shack",
    amount: 28.50,
    category: "dining",
    cardUsed: "amex-gold",
    cardUsedName: "Amex Gold",
    optimalCard: "amex-gold",
    optimalCardName: "Amex Gold",
    missedValue: 0,
    isOptimal: true,
  },
  {
    id: "txn-026",
    date: "2025-01-18",
    merchant: "Marriott Times Square",
    amount: 549.00,
    category: "travel",
    cardUsed: "chase-sapphire-preferred",
    cardUsedName: "Chase Sapphire Preferred",
    optimalCard: "chase-sapphire-preferred",
    optimalCardName: "Chase Sapphire Preferred",
    missedValue: 0,
    isOptimal: true,
  },
  {
    id: "txn-027",
    date: "2025-01-15",
    merchant: "Kroger",
    amount: 178.32,
    category: "groceries",
    cardUsed: "chase-freedom-unlimited",
    cardUsedName: "Chase Freedom Unlimited",
    optimalCard: "amex-gold",
    optimalCardName: "Amex Gold",
    missedValue: 4.46,
    isOptimal: false,
  },
  {
    id: "txn-028",
    date: "2025-01-12",
    merchant: "Exxon",
    amount: 70.00,
    category: "gas",
    cardUsed: "chase-freedom-unlimited",
    cardUsedName: "Chase Freedom Unlimited",
    optimalCard: "amex-blue-cash-preferred",
    optimalCardName: "Amex Blue Cash Preferred",
    missedValue: 1.05,
    isOptimal: false,
  },
  {
    id: "txn-029",
    date: "2025-01-10",
    merchant: "Le Bernardin",
    amount: 280.00,
    category: "dining",
    cardUsed: "amex-gold",
    cardUsedName: "Amex Gold",
    optimalCard: "amex-gold",
    optimalCardName: "Amex Gold",
    missedValue: 0,
    isOptimal: true,
  },
  {
    id: "txn-030",
    date: "2025-01-05",
    merchant: "Apple TV+",
    amount: 9.99,
    category: "streaming",
    cardUsed: "chase-freedom-unlimited",
    cardUsedName: "Chase Freedom Unlimited",
    optimalCard: "amex-blue-cash-preferred",
    optimalCardName: "Amex Blue Cash Preferred",
    missedValue: 0.40,
    isOptimal: false,
  },
];

export const getMissedValueTotal = (): number =>
  MOCK_TRANSACTIONS.reduce((sum, t) => sum + t.missedValue, 0);

export const getTransactionsByCategory = (): Record<string, Transaction[]> => {
  const grouped: Record<string, Transaction[]> = {};
  for (const t of MOCK_TRANSACTIONS) {
    if (!grouped[t.category]) grouped[t.category] = [];
    grouped[t.category].push(t);
  }
  return grouped;
};
